# Generated by Django 6.0.2 on 2026-02-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_dzd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (DZD)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('duration', models.CharField(max_length=100, verbose_name='Durée')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['start_date'],
            },
        ),
    ]
