# Generated by Django 6.0.2 on 2026-02-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_training_category'),
    ]

    operations = [
    ]
