# Generated by Django 5.2.1 on 2026-02-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_populate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='training',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la vidéo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('video_file', models.FileField(upload_to='course_videos/', verbose_name='Fichier Vidéo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre de lecture')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.training', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Leçon Vidéo',
                'verbose_name_plural': 'Leçons Vidéos',
                'ordering': ['order'],
            },
        ),
    ]
