# Generated by Django 6.0.2 on 2026-02-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_category_id_alter_training_id_videolesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Durée en secondes'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='training',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
