# Generated by Django 6.0.2 on 2026-02-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_training_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Répondu le'),
        ),
        migrations.AddField(
            model_name='teachermessage',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='Réponse du formateur'),
        ),
    ]
