# Generated by Django 5.2.1 on 2026-03-07 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coupon_book_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-submitted_at', 'start_date'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AddField(
            model_name='training',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Raison du refus'),
        ),
        migrations.AddField(
            model_name='training',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revu le'),
        ),
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='approved', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='training',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Soumis le'),
        ),
        migrations.AddField(
            model_name='training',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_courses', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par'),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Durée'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='courses.conversation', verbose_name='Conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.DeleteModel(
            name='TeacherMessage',
        ),
    ]
