# Generated by Django 5.2.1 on 2026-03-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_training_options_training_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='chargily_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='checkout_url',
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery_commune',
            field=models.CharField(blank=True, max_length=100, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery_wilaya',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wilaya'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypart_invitation_uuid',
            field=models.CharField(blank=True, max_length=255, verbose_name='UUID Invitation Paypart'),
        ),
        migrations.AddField(
            model_name='payment',
            name='redirection_tag',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Tag de redirection'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('canceled', 'Annulé')], default='pending', max_length=10, verbose_name='Statut'),
        ),
    ]
