# Generated by Django 5.2.1 on 2026-03-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_payment_chargily_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accès expire le'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='item_type',
            field=models.CharField(choices=[('course', 'Formation'), ('book', 'Livre'), ('conversation', 'Abonnement Messagerie')], max_length=20, verbose_name='Type'),
        ),
    ]
