# Generated by Django 6.0.2 on 2026-02-28 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='Photo de profil')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('speciality', models.CharField(blank=True, max_length=255, verbose_name='Spécialité')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Formateur',
                'verbose_name_plural': 'Profils Formateurs',
            },
        ),
    ]
