# Generated by Django 5.2.1 on 2026-03-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_alter_brandrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
