# Generated by Django 6.0.2 on 2026-03-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_alter_brandrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
